#!/bin/bash

# This creates a new plugin based on micrositeComponentBoilerplate repo

############################
# usage:
# $ ./bootstrap pluginName 'description of the plugin'
#
# notes:
# plugin will be created off of parent directory
############################

########## Variables
plugin=$1
description=$2

########## Script
echo "creating ${plugin} plugin..."
cd ..
git clone https://github.com/okize/micrositeComponentBoilerplate.git $plugin
cd $plugin
rm -rf ./.git
for file in `find . -name 'pluginName.*'`; do
  mv "$file" "${file/pluginName/$plugin}"
done
echo 'creating readme file'
echo $description > readme.md
for file in $(grep -r -l '/{{pluginName}}' ./*) ; do
  sed "s/{{pluginName}}/$plugin/g" $file > $file.$$ && mv $file.$$ $file
done
# cat makefile | pbcopy && echo "SCRIPT_NAME = ${plugin}" > makefile && pbpaste >> makefile
# mv makefile.tmp makefile
make
# git init
# git add . && git commit -m 'initial commit'
# echo hub create -d "'${description}'"
# git push -u origin master
#rm bootstrap